### ISSUE TITLE
Any release plan for this package?

### ISSUE THREAD

**Issue by lostncg** [CleverTap/clevertap-web-sdk#14]
As title described, can I know the release date for this package?

**Comment by avinashdaiict** [comment]
Can we use it on production ?

**Comment by royson-ct** [comment]
@lostncg @avinashdaiict you can go ahead and use this in production. We are maintaining the beta versioning while we test backward compatibility with legacy CleverTap Web SDK.

Would be great if you could share the website where you are planning to use CleverTap Web SDK. 😃
