### ISSUE TITLE
Privacy settings changes after init

### ISSUE THREAD

**Issue by segux** [CleverTap/clevertap-web-sdk#197]
Hi, we have cookiebot for cookie consent.

Im starting clevertap before if user accepted or not cookie consent.

Can we change privacy settings after init?

**Comment by PraveenCTzen** [comment]
Hey,

Just a quick check-in to clarify something: Are you looking to modify cookie permission settings or CleverTap privacy settings?

For instance, in CleverTap, you might use:
clevertap.privacy.push({optOut: false}); // Set the flag to true if the user opts out of sharing their data.
