### ISSUE TITLE
Need a maintainer for type-definitions

### ISSUE THREAD

**Issue by droyson** [CleverTap/clevertap-web-sdk#40]
@pwilkniss @Aditi3 @kunl-code created type-definitions for this repo: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57546. This will be live in a couple of hours and can be installed via npm.
```bash
npm install --save-dev @types/clevertap-web-sdk
```
or yarn
```bash
yarn add --dev @types/clevertap-web-sdk
```

Can you suggest someone who can maintain this repo for future. Will add them to the repo: https://github.com/droyson/DefinitelyTyped/tree/clevertap-web-sdk

**Comment by pwilkniss** [comment]
hey @droyson !  can you add @darshanclevertap and @akashvercetti thanks!
