### ISSUE TITLE
Clevertap latest version 1.1.0 is adding the default region

### ISSUE THREAD

**Issue by narender2031** [CleverTap/clevertap-web-sdk#41]
```
clevertap.init('account_id', '', API.CLEVERTAP_PROXY);
```
when we are passing the empty string for the `REGION` in clevertap init function, it starts loading the random region for in in API url  `https://eu1.s.myproxyurl.com/`. 

It should be like this. `https://s.myproxyurl.com/`. 

To reproduce this issue please use the `1.1.0` latest version. 

For now, I am using the `1.0.0`. It  is working fine.

**Comment by akashvercetti** [comment]
Hi @narender2031 thanks for bringing this up. We'll implement a fix and update the package as soon as possible.

**Comment by akashvercetti** [comment]
Hi @narender2031 , this bug has been fixed in v1.1.1.
