### ISSUE TITLE
Using String.prototype.trim wrongly on the boolean value stored in local storage

### ISSUE THREAD

**Issue by lostncg** [CleverTap/clevertap-web-sdk#47]
We received an error reported from our Sentry monitor, mentioned the clevertap web SDK is throwing an error as screenshot below shown.
![image](https://user-images.githubusercontent.com/11206864/147376119-f8b3234b-97ff-4d59-9854-3481d1218418.png)

After tracing the root cause, we found that this is because the SDK never consider boolean value while checking the clevertap data stored in the localstorage.
![image](https://user-images.githubusercontent.com/11206864/147376096-9c15b1fd-c214-49af-afbb-ceed625f950c.png)
![image](https://user-images.githubusercontent.com/11206864/147376104-97e2d17d-f59a-45af-8e3f-5ffa58bd54e6.png)

I think that is quite clear in how to fix the bug, lets me know if you need me to submit a PR 😄

**Comment by akashvercetti** [comment]
@lostncg Thanks for bringing this up. We'll update the package with a fix as soon as possible.

**Comment by akshaysr-buku** [comment]
@akashvercetti  when will this be resolved? please publish it ASAP 
Thank you.

**Comment by akashvercetti** [comment]
Hello. A fix has been added with the latest update. 
Thank you.
