### ISSUE TITLE
Getting ReferenceError: window is not defined, when clevertap is initialised  in _app.tsx file of NextJs

### ISSUE THREAD

**Issue by akshaysr-buku** [CleverTap/clevertap-web-sdk#52]
Whenver i use Clevertap in NextJs _app.tsx
i am getting the below error 
<img width="1440" alt="Screenshot 2022-01-04 at 7 02 21 PM" src="https://user-images.githubusercontent.com/95604746/148066698-f1fbb75c-7d23-4f5e-b22e-4674bb85f4b0.png">

If the package isn't compatible with Next.js, is there any way I cal initialize clevertap in my App?

**Comment by akshaysr-buku** [comment]
@akashvercetti

**Comment by akashvercetti** [comment]
Hi @akshaysr-buku , our SDK is a typically a client side only library and does not by its nature support SSR. 
Having said that, there might be a workaround here: https://github.com/CleverTap/clevertap-web-sdk/issues/39 
or
you could try `npm install --save-dev @types/clevertap-web-sdk` since type-definitions have been created at: [DefinitelyTyped/DefinitelyTyped#57546. ](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57546)

**Comment by abhu-A-J** [comment]
Hi @akashvercetti we also use the clever tap at our organization which runs a Next.js app.

We use it using the following strategy, without relying on the SDK.

1. Create an analytics component, which uses the [Next.js Script component ](https://nextjs.org/docs/basic-features/script) to inject the script 
```tsx
import Script from 'next/script'

function Analytics(){
     return (
	<Script strategy="afterInteractive" id="clevertap-script" src="https://d2r1yp2w7bby2u.cloudfront.net/js/a.js" />
	<Script id="clevertap-analytics" strategy="afterInteractive" 
                    dangerouslySetInnerHTML={{ __html:`
                                    var clevertap = {event:[], profile:[], account:[], onUserLogin:[], notifications:[], privacy:[]};
                                    clevertap.account.push({"id": "${clevertapAccountId}"});
                                    clevertap.privacy.push({optOut: false}); 
                                    clevertap.privacy.push({useIP: true});` }}
	/>
      )
 
}

```

2. You can use this component using the dynamic import in _app.tsx

```ts
const Analytics = dynamic(() => import('@components/analytics'), { ssr: false });


function MyApp({ Component: AppComponent, pageProps }: AppProps) {
	return (
			<AppComponent {...pageProps} />
			<Analytics />		
	);
}
```

3. Using clever tap to send events etc.

If you are using typescript you can write your own types for payload depending on your use case.

```tsx

export type WindowWithAnalytics = Window &
	typeof globalThis & {	
		clevertap: any;	// write more types here if you want
};
	
class Analytics{
	isWindowRuntime= typeof window !==='undefined'
	   pushEvent(eventName,payload){
	       (window as WindowWithAnalytics).clevertap.event.push(eventName, payload);
          }
          
          
}

// usage

 Analytics.pushEvent('Login',{
          //details
})
	
```

Hopefully, this helps!

**Comment by akshaysr-buku** [comment]
Thanks @abhu-A-J
