### ISSUE TITLE
Can't save a webhook!

### ISSUE THREAD

**Issue by ebellumat** [CleverTap/clevertap-web-sdk#54]
This is a bug on the admin pages of Clevertap. I want to save my Webhook configuration but i receive a 502 error.

https://eu1.dashboard.clevertap.com/ZR9-7ZR-546Z/account-setup/campaigns-journeys/channels/webhooks

![image](https://user-images.githubusercontent.com/26942680/157967119-11635946-12de-4c0a-a155-0d50e007155d.png)

Please, tell someone to fix this. It's very urgent.

**Comment by darshanclevertap** [comment]
@ebellumat Are you still facing this issue? I would suggest raising a support ticket via the CleverTap Dashboard since this repo is only for the CleverTap Web SDK.
