### ISSUE TITLE
Using Clevertap through Partytown 

### ISSUE THREAD

**Issue by abhu-A-J** [CleverTap/clevertap-web-sdk#55]
Hi @akashvercetti.  We use the clever tap as our analytics tool at our organization and recently have been trying to port all our third-party libraries through [Partytown](https://partytown.builder.io/) and wanted to know if you plan our adding support (docs on party town) for it as well?

Although Partytown runs with almost zero configuration, depending upon the library we are using we need to set up the correct event forwarding and proxies.

Just wanted to know if a clever tap can be used via Partytown or not?

Would love to help write docs and examples with setting it up if it's possible (since I'm not very well aware of clever tap internals) and bring it to the official list [here ](https://partytown.builder.io/common-services)

Plus the option to alter type of script is some config would be great so we can run it through PT.

```tsx
	<Partytown
		debug
		forward={[
			'clevertap',
			'clevertap.account',
			'clevertap.clear',
			'clevertap.event.push',
			'clevertap.event.getDetails',
			'clevertap.getClevertapID',
			'clevertap.logout',
			'clevertap.notifications.push',
			'clevertap.onUserLogin.push',
			'clevertap.privacy.push',
			'clevertap.profile.push',
			'clevertap.profile.getAttribute',
			'clevertap.session.getPageCount',
			'clevertap.session.getTimeElapsed',
			'clevertap.user.getLastVisit',
			'clevertap.user.getTotalVisits'
		]}
		resolveUrl={()=>{
		// setup reverse proxies if needed
		}}
	/>

```

**Comment by abhu-A-J** [comment]
@akashvercetti just wanted to sync again regarding your thoughts on this?

**Comment by KambleSonam** [comment]
@abhu-A-J Closing this ticket. Kindly create new issue if issue still persist.
