### ISSUE TITLE
Clevertap init function return error

### ISSUE THREAD

**Issue by narender2031** [CleverTap/clevertap-web-sdk#67]
Console Error: 
```
logger.js:56 CleverTap [1658898472908]: CleverTap error: Incorrect embed script.
```
<img width="848" alt="Screenshot 2022-07-27 at 10 40 30 AM" src="https://user-images.githubusercontent.com/25151772/181166262-2f5ccd9e-c491-4329-b8d9-d4cef886da09.png">

Clevertap version: `1.2.0`

I am not able to understand this error. Can someone help me to understand the error and solution for this. 

My application is Sveltekit SSR 

Clevertap Setup
```
let clevertap;

export async function ctInit(id: string) {
	if (!window) return

	const clevertapInit = await import('clevertap-web-sdk')
	clevertap = clevertapInit.default

	// replace with the CLEVERTAP_ACCOUNT_ID with the actual ACCOUNT ID value from your Dashboard -> Settings page
	clevertap.init(id, '', API.CLEVERTAP_PROXY);
	clevertap.privacy.push({ optOut: false }); //set the flag to true, if the user of the device opts out of sharing their data
	clevertap.privacy.push({ useIP: false }); //set the flag to true, if the user agrees to share their IP data
	clevertap.spa = true;
}
```

@akashvercetti @abhu-A-J

**Comment by KambleSonam** [comment]
@narender2031  This error occurs only when the id passed in init is an empty string. Do make sure that id is not empty.

**Comment by narender2031** [comment]
This is issue is resolved. We can close this @KambleSonam
