### ISSUE TITLE
Unable to send Array as Event Property

### ISSUE THREAD

**Issue by akshaysr-buku** [CleverTap/clevertap-web-sdk#81]
Hey @akashvercetti @pranaywarke I am unable to send Array of string as Event Property in Clevertap web SDK, i am getting the below Error, Is it possible to send Array of string/boolean as event property or is there any work Around to send Array as Event Property? please let me know.

<img width="642" alt="Screenshot 2022-09-07 at 11 43 59 AM" src="https://user-images.githubusercontent.com/95604746/188802356-0a969614-4a5b-4d0e-93b5-2f9789536ecd.png">

**Comment by akshaysr-buku** [comment]
@akashvercetti The verison i am using is 1.1.0

**Comment by KambleSonam** [comment]
@akshaysr-buku Currently we don't have value support in the event array. 
https://developer.clevertap.com/docs/events#adding-properties-to-a-custom-event
Kindly let us know the format in which you are trying to send the event ?

**Comment by akshaysr-buku** [comment]
@KambleSonam i want to send an EventProperty like below , in which `Loan_application_id` and `Loan_application_status` is array of string
`
{
        "Loan_application_id": ["caf7608d-04ed-4fb1-89ba-fa7ae22118bf"],
        "Loan_application_status": ["DRAFT","NA"],
        "Landing_page_type": "NoCondition_PageView"
}
`

**Comment by KambleSonam** [comment]
@akshaysr-buku The event structure specified is not supported . We will add it to our to-do's. Thank You.

**Comment by akshaysr-buku** [comment]
Hey @KambleSonam do Clevertap supports Array of event properties now? or any update on same?
Thank you
