### ISSUE TITLE
request:  support of proxy domain for web

### ISSUE THREAD

**Issue by abhu-A-J** [CleverTap/clevertap-web-sdk#96]
Hi Clevertap Team,

I wanted to confirm if web SDK supports a way to provide an option for a proxy domain on web SDK, similar to [ios SDK's](https://developer.clevertap.com/docs/ios-custom-proxy-domain)

I was not able to find the option on docs , so wanted if there is a way to achieve this.

**Comment by sinhaayush7** [comment]
Hi @abhu-A-J . We have a support for Proxy Domain. You can read about it more over here under Basic Initialisation Section- https://github.com/CleverTap/clevertap-web-sdk#readme

**Comment by abhu-A-J** [comment]
> Hi @abhu-A-J . We have a support for Proxy Domain. You can read about it more over here under Basic Initialisation Section- https://github.com/CleverTap/clevertap-web-sdk#readme

Hello @sinhaayush7 we use inline scripts directly over web-sdk, could you recommend the solution to that. The above link suggests only for web SDK. Thank you for the response.

**Comment by sinhaayush7** [comment]
hey @abhu-A-J this looks right.

**Comment by abhu-A-J** [comment]
> hey @abhu-A-J this looks right. Does this solve your issue?

Hey @sinhaayush7 , thanks!!!

 I can see some warning/information by turning on logger `sessionStorage['WZRK_D']=''` which shows these messages and no requests are being made. Any idea on what can be causing these???? 

![Screenshot 2022-12-23 at 4 45 43 PM](https://user-images.githubusercontent.com/49617450/209327070-1303e882-7379-4059-bc7a-1d2aa395e047.png)

**Comment by abhu-A-J** [comment]
@sinhaayush7  this is resolved per v1.3.5. 

Thanks for the help, I will be marking the issues as resolved, and if in future the problem occurs again, I will open up the discussion again.

Thanks for the support.
