### ISSUE TITLE
ios proxy setup: proxy domain does not give 200 with no respose body

### ISSUE THREAD

**Issue by abhu-A-J** [CleverTap/clevertap-web-sdk#97]
Hi, there Clevertap team.

Due to analytics packet drops on ios devices, we decided to run clever tap by using a custom reverse proxy on our server and followed through the steps mentioned on the [docs](https://developer.clevertap.com/docs/ios-custom-proxy-domain)

Although the proxy setup seems to be running fine, we could see our events get populated, we do not receive any response body when hitting the API through curl or similar, unlike the original domain which returns a response body.

**Status code of 200 with empty body. (proxy domain)**

```
https://{proxyDomain}/a?t=96&type=push&d=N4IgLgngDgpiBcIoCcD2AzAlgGzgGiTS1wVAGMwB9VKMVAVzAXQENsBnGAXwMwBMEIAEoBWAJwBaANIB2KRJEAWAGwAtEAQDmg9GICMygBzpdZMnsWKARgAYZVgEx7zZGOjKOxRq8o0h2CAYyNiIyimGGBFDa8A5cQA%3D&optOut=false&rn=1&i=1670574827&sn=0&gc=f9168ff9cc144b07b21c1cefcb2968b6&arp=N4Ig1g%2BgdiBcIG0AEAdEBqAnARkwDgBYBWABgIDZy9M0kAaVEfYsy6tAXRDpACto4IAJoAmAA68ApgHchAQW4gAlgPiiiYAGYBzAIoBhRQBMIAFwDOcEjyMALKzwBucbD36X4wJAF9FSo4IASkSYALQA0gDs4aFEFABaipJmHtYgAE4pLuSRJESRBAV4PErmAPIAqgAycKbpAK6S3kAAAA%3D%3D&tries=1&useIP=true&r=1670574827575
```

**Status code of 200 with body which has a response. (OG API)**
```
https://eu1.clevertap-prod.com/a?t=96&type=push&d=N4IgLgngDgpiBcIoCcD2AzAlgGzgGiTS1wVAGMwB9VKMVAVzAXQENsBnGAXwMwBMEIAEoBWAJwBaANIB2KRJEAWAGwAtEAQDmg9GICMygBzpdZMnsWKARgAYZVgEx7zZGOjKOxRq8o0h2CAYyNiIyimGGBFDa8A5cQA%3D&optOut=false&rn=1&i=1670574827&sn=0&gc=f9168ff9cc144b07b21c1cefcb2968b6&arp=N4Ig1g%2BgdiBcIG0AEAdEBqAnARkwDgBYBWABgIDZy9M0kAaVEfYsy6tAXRDpACto4IAJoAmAA68ApgHchAQW4gAlgPiiiYAGYBzAIoBhRQBMIAFwDOcEjyMALKzwBucbD36X4wJAF9FSo4IASkSYALQA0gDs4aFEFABaipJmHtYgAE4pLuSRJESRBAV4PErmAPIAqgAycKbpAK6S3kAAAA%3D%3D&tries=1&useIP=true&r=1670574827575
```

Can you help us with what might be causing this/ or do we need additional setup on clkoudfront to get back the origin response body on viewer request?  Assuming the incoming body is used by the SDK itself ??

**Comment by sinhaayush7** [comment]
Hi @abhu-A-J , the docs that you mentioned are for IOS. It would help us replicating the issue if you can provide us with a sample code. Also can you please elaborate what your'e trying to achieve over here.

**Comment by abhu-A-J** [comment]
Hi @sinhaayush7  I think a part of it is also related to #96 ...

I could see from [here](https://github.com/CleverTap/clevertap-web-sdk/blob/master/src/clevertap.js#L372) and [here](https://github.com/CleverTap/clevertap-web-sdk/blob/master/src/modules/account.js#L9)


Will the configuration of inline scripts suffice the setup.

```
var clevertap = {event:[], profile:[], account:[], onUserLogin:[], notifications:[], privacy:[], targetDomain: 'PROXY_DOMAIN'};
clevertap.account.push({"id": "${clevertapAccountId}"});
clevertap.privacy.push({optOut: false}); 
clevertap.privacy.push({useIP: true});

```
